train_batch_size: 32
train_micro_batch_size_per_gpu: 4
steps_per_print: 10
zero_optimization:
    stage: 2
    offload_param:
        device: &device cpu
    offload_optimizer:
        device: *device
    stage3_param_persistence_threshold: 1e4
    stage3_max_live_parameters: 3e7
    stage3_prefetch_bucket_size: 3e7
    memory_efficient_linear: False
fp16:
    enabled: True
    loss_scale_window: 100
gradient_clipping: 1.0
prescale_gradients: False
wall_clock_breakdown: False
hybrid_engine:
    enabled: False
    inference_tp_size: 1
    release_inference_cache: False
    pin_parameters: True
    tp_gather_partition_size: 8